#!/usr/bin/env ruby
require 'highline/import'
Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

if ARGV.length < 1
  print "[Help] Run as: ./idea_bank manage\n"
elsif ARGV.length == 1
  if ARGV[0] != 'manage'
    print "[Help] Run as: ./idea_bank manage\n"
  else
    choose do |menu|
      menu.prompt = ""

      projects_controller = ProjectsController.new
      menu.choice('Add project') { say("Enter project name.\n") }
      menu.choice('Update project') { say("What project would you like to update?\n") }
      menu.choice('Delete project') { say("What project would you like to delete?\n") }
      menu.choice('View all projects') { say(projects_controller.index) }
    end
  end
end