#!/usr/bin/env ruby
require 'highline/import'
Dir["./lib/*.rb"].each { |f| require f }
Dir["./app/**/*.rb"].each { |f| require f }

MENU_FORMAT = "----------------------------------------------------------------------\n"
WIDTH = 70

if ARGV.size == 1 and ARGV[0] == "manage"
  ProjectsController.manage_menu
else
  puts "[Help] Run as: ./idea_bank manage"
end